/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
>;

export type Tag = {
  _id: string;
  _type: 'tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Portfolio = {
  _id: string;
  _type: 'portfolio';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  content?: BlockContent;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  tags?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  githubUrl?: string;
  frontendGithubUrl?: string;
  liveUrl?: string;
  isPublished?: boolean;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  content?: BlockContent;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  tags?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'tag';
  }>;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  isPublished?: boolean;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Code = {
  _type: 'code';
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BlockContent
  | Tag
  | Slug
  | Portfolio
  | SanityImageCrop
  | SanityImageHotspot
  | Blog
  | Category
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(_createdAt desc) { _id, name, slug }
export type CategoriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
}>;
// Variable: categoryBySlugQuery
// Query: *[_type == "category" && slug.current == $slug][0] { _id, name, slug }
export type CategoryBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
} | null;
// Variable: trendingCategoriesQuery
// Query: *[_type == "category"] | order(_createdAt desc)[0...10] { _id, name, slug }
export type TrendingCategoriesQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
}>;
// Variable: tagsQuery
// Query: *[_type == "tag"] | order(_createdAt desc) { _id, name, slug }
export type TagsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
}>;
// Variable: tagBySlugQuery
// Query: *[_type == "tag" && slug.current == $slug][0] { _id, name, slug }
export type TagBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
} | null;
// Variable: blogsQuery
// Query: *[_type == "blog"] | order(_createdAt desc) {  _id,  title,  slug,  description,  featuredImage,  _createdAt,  category->{ _id, name, slug }}
export type BlogsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  _createdAt: string;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;
// Variable: trendingBlogsQuery
// Query: *[_type == "blog"] | order(_createdAt desc)[0...5] {  _id,  title,  slug,  description,  featuredImage,  _createdAt,  category->{ _id, name, slug }}
export type TrendingBlogsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  _createdAt: string;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;
// Variable: blogBySlugQuery
// Query: *[_type == "blog" && slug.current == $slug][0] {    _id,    title,    slug,    description,    content,    featuredImage,    _createdAt,    _updatedAt,    category->{ _id, name, slug },    tags[]->{ _id, name, slug }  }
export type BlogBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  content: BlockContent | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  _createdAt: string;
  _updatedAt: string;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
} | null;
// Variable: blogByIdQuery
// Query: *[_type == "blog" && _id == $id][0] {    _id,    title,    slug,    description,    content,    featuredImage,    _createdAt,    _updatedAt,    category->{ _id, name, slug },    tags[]->{ _id, name, slug }  }
export type BlogByIdQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  content: BlockContent | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  _createdAt: string;
  _updatedAt: string;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
} | null;
// Variable: blogSearchQuery
// Query: *[_type == "blog" && title match $keyword + "*"] | order(_createdAt desc) {    _id, title, slug  }
export type BlogSearchQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;
// Variable: portfoliosQuery
// Query: *[_type == "portfolio"] | order(_createdAt desc) {  _id,  title,  slug,  description,  featuredImage,  _createdAt,  category->{ _id, name, slug }}
export type PortfoliosQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  _createdAt: string;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;
// Variable: featuredPortfoliosQuery
// Query: *[_type == "portfolio"] | order(_createdAt desc)[0...5] {  _id,  title,  slug,  description,  featuredImage,  _createdAt,  category->{ _id, name, slug }}
export type FeaturedPortfoliosQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  _createdAt: string;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
}>;
// Variable: portfolioBySlugQuery
// Query: *[_type == "portfolio" && slug.current == $slug][0] {    _id,    title,    slug,    description,    content,    featuredImage,    _createdAt,    _updatedAt,    githubUrl,    frontendGithubUrl,    liveUrl,    category->{ _id, name, slug },    tags[]->{ _id, name, slug }  }
export type PortfolioBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  content: BlockContent | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  _createdAt: string;
  _updatedAt: string;
  githubUrl: string | null;
  frontendGithubUrl: string | null;
  liveUrl: string | null;
  category: {
    _id: string;
    name: string | null;
    slug: Slug | null;
  } | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
} | null;
// Variable: portfolioSearchQuery
// Query: *[_type == "portfolio" && title match $keyword + "*"] | order(_createdAt desc) {    _id, title, slug  }
export type PortfolioSearchQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;
// Variable: combinedSearchQuery
// Query: {    "blogs": *[_type == "blog" && title match $keyword + "*"] | order(_createdAt desc) {      _id, title, slug    },    "projects": *[_type == "portfolio" && title match $keyword + "*"] | order(_createdAt desc) {      _id, title, slug    },    "categories": *[_type == "category" && name match $keyword + "*"] | order(_createdAt desc) {      _id, name, slug    },    "tags": *[_type == "tag" && name match $keyword + "*"] | order(_createdAt desc) {      _id, name, slug    }  }
export type CombinedSearchQueryResult = {
  blogs: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }>;
  projects: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }>;
  categories: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }>;
};

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "category"] | order(_createdAt desc) { _id, name, slug }': CategoriesQueryResult;
    '*[_type == "category" && slug.current == $slug][0] { _id, name, slug }': CategoryBySlugQueryResult;
    '*[_type == "category"] | order(_createdAt desc)[0...10] { _id, name, slug }': TrendingCategoriesQueryResult;
    '*[_type == "tag"] | order(_createdAt desc) { _id, name, slug }': TagsQueryResult;
    '*[_type == "tag" && slug.current == $slug][0] { _id, name, slug }': TagBySlugQueryResult;
    '*[_type == "blog"] | order(_createdAt desc) {\n  _id,\n  title,\n  slug,\n  description,\n  featuredImage,\n  _createdAt,\n  category->{ _id, name, slug }\n}': BlogsQueryResult;
    '*[_type == "blog"] | order(_createdAt desc)[0...5] {\n  _id,\n  title,\n  slug,\n  description,\n  featuredImage,\n  _createdAt,\n  category->{ _id, name, slug }\n}': TrendingBlogsQueryResult;
    '*[_type == "blog" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    content,\n    featuredImage,\n    _createdAt,\n    _updatedAt,\n    category->{ _id, name, slug },\n    tags[]->{ _id, name, slug }\n  }': BlogBySlugQueryResult;
    '*[_type == "blog" && _id == $id][0] {\n    _id,\n    title,\n    slug,\n    description,\n    content,\n    featuredImage,\n    _createdAt,\n    _updatedAt,\n    category->{ _id, name, slug },\n    tags[]->{ _id, name, slug }\n  }': BlogByIdQueryResult;
    '*[_type == "blog" && title match $keyword + "*"] | order(_createdAt desc) {\n    _id, title, slug\n  }': BlogSearchQueryResult;
    '*[_type == "portfolio"] | order(_createdAt desc) {\n  _id,\n  title,\n  slug,\n  description,\n  featuredImage,\n  _createdAt,\n  category->{ _id, name, slug }\n}': PortfoliosQueryResult;
    '*[_type == "portfolio"] | order(_createdAt desc)[0...5] {\n  _id,\n  title,\n  slug,\n  description,\n  featuredImage,\n  _createdAt,\n  category->{ _id, name, slug }\n}': FeaturedPortfoliosQueryResult;
    '*[_type == "portfolio" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    content,\n    featuredImage,\n    _createdAt,\n    _updatedAt,\n    githubUrl,\n    frontendGithubUrl,\n    liveUrl,\n    category->{ _id, name, slug },\n    tags[]->{ _id, name, slug }\n  }': PortfolioBySlugQueryResult;
    '*[_type == "portfolio" && title match $keyword + "*"] | order(_createdAt desc) {\n    _id, title, slug\n  }': PortfolioSearchQueryResult;
    '{\n    "blogs": *[_type == "blog" && title match $keyword + "*"] | order(_createdAt desc) {\n      _id, title, slug\n    },\n    "projects": *[_type == "portfolio" && title match $keyword + "*"] | order(_createdAt desc) {\n      _id, title, slug\n    },\n    "categories": *[_type == "category" && name match $keyword + "*"] | order(_createdAt desc) {\n      _id, name, slug\n    },\n    "tags": *[_type == "tag" && name match $keyword + "*"] | order(_createdAt desc) {\n      _id, name, slug\n    }\n  }': CombinedSearchQueryResult;
  }
}
